# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pedidos.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpedidos.proto\x12\x07pedidos\"K\n\x15RealizarPedidoRequest\x12\x12\n\nusuario_id\x18\x01 \x01(\t\x12\x1e\n\x06livros\x18\x02 \x03(\x0b\x32\x0e.pedidos.Livro\"$\n\x16RealizarPedidoResponse\x12\n\n\x02id\x18\x01 \x01(\t\"-\n\x17HistoricoPedidosRequest\x12\x12\n\nusuario_id\x18\x01 \x01(\t\"V\n\x06Pedido\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nusuario_id\x18\x02 \x01(\t\x12\x1e\n\x06livros\x18\x03 \x03(\x0b\x32\x0e.pedidos.Livro\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\"<\n\x18HistoricoPedidosResponse\x12 \n\x07pedidos\x18\x01 \x03(\x0b\x32\x0f.pedidos.Pedido\"<\n\x1aObterDetalhesPedidoRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nusuario_id\x18\x02 \x01(\t\"W\n\x1bObterDetalhesPedidoResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x1e\n\x06livros\x18\x03 \x03(\x0b\x32\x0e.pedidos.Livro\"+\n\x05Livro\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x12\n\nquantidade\x18\x02 \x01(\x05\x32\xa6\x02\n\rGestaoPedidos\x12Q\n\x0eRealizarPedido\x12\x1e.pedidos.RealizarPedidoRequest\x1a\x1f.pedidos.RealizarPedidoResponse\x12`\n\x19RecuperarHistoricoPedidos\x12 .pedidos.HistoricoPedidosRequest\x1a!.pedidos.HistoricoPedidosResponse\x12`\n\x13ObterDetalhesPedido\x12#.pedidos.ObterDetalhesPedidoRequest\x1a$.pedidos.ObterDetalhesPedidoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pedidos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REALIZARPEDIDOREQUEST']._serialized_start=26
  _globals['_REALIZARPEDIDOREQUEST']._serialized_end=101
  _globals['_REALIZARPEDIDORESPONSE']._serialized_start=103
  _globals['_REALIZARPEDIDORESPONSE']._serialized_end=139
  _globals['_HISTORICOPEDIDOSREQUEST']._serialized_start=141
  _globals['_HISTORICOPEDIDOSREQUEST']._serialized_end=186
  _globals['_PEDIDO']._serialized_start=188
  _globals['_PEDIDO']._serialized_end=274
  _globals['_HISTORICOPEDIDOSRESPONSE']._serialized_start=276
  _globals['_HISTORICOPEDIDOSRESPONSE']._serialized_end=336
  _globals['_OBTERDETALHESPEDIDOREQUEST']._serialized_start=338
  _globals['_OBTERDETALHESPEDIDOREQUEST']._serialized_end=398
  _globals['_OBTERDETALHESPEDIDORESPONSE']._serialized_start=400
  _globals['_OBTERDETALHESPEDIDORESPONSE']._serialized_end=487
  _globals['_LIVRO']._serialized_start=489
  _globals['_LIVRO']._serialized_end=532
  _globals['_GESTAOPEDIDOS']._serialized_start=535
  _globals['_GESTAOPEDIDOS']._serialized_end=829
# @@protoc_insertion_point(module_scope)
