# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pedidos_pb2 as pedidos__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pedidos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GestaoPedidosStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RealizarPedido = channel.unary_unary(
                '/pedidos.GestaoPedidos/RealizarPedido',
                request_serializer=pedidos__pb2.RealizarPedidoRequest.SerializeToString,
                response_deserializer=pedidos__pb2.RealizarPedidoResponse.FromString,
                _registered_method=True)
        self.RecuperarHistoricoPedidos = channel.unary_unary(
                '/pedidos.GestaoPedidos/RecuperarHistoricoPedidos',
                request_serializer=pedidos__pb2.HistoricoPedidosRequest.SerializeToString,
                response_deserializer=pedidos__pb2.HistoricoPedidosResponse.FromString,
                _registered_method=True)
        self.ObterDetalhesPedido = channel.unary_unary(
                '/pedidos.GestaoPedidos/ObterDetalhesPedido',
                request_serializer=pedidos__pb2.ObterDetalhesPedidoRequest.SerializeToString,
                response_deserializer=pedidos__pb2.ObterDetalhesPedidoResponse.FromString,
                _registered_method=True)


class GestaoPedidosServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RealizarPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecuperarHistoricoPedidos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterDetalhesPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GestaoPedidosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RealizarPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.RealizarPedido,
                    request_deserializer=pedidos__pb2.RealizarPedidoRequest.FromString,
                    response_serializer=pedidos__pb2.RealizarPedidoResponse.SerializeToString,
            ),
            'RecuperarHistoricoPedidos': grpc.unary_unary_rpc_method_handler(
                    servicer.RecuperarHistoricoPedidos,
                    request_deserializer=pedidos__pb2.HistoricoPedidosRequest.FromString,
                    response_serializer=pedidos__pb2.HistoricoPedidosResponse.SerializeToString,
            ),
            'ObterDetalhesPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterDetalhesPedido,
                    request_deserializer=pedidos__pb2.ObterDetalhesPedidoRequest.FromString,
                    response_serializer=pedidos__pb2.ObterDetalhesPedidoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pedidos.GestaoPedidos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pedidos.GestaoPedidos', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GestaoPedidos(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RealizarPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pedidos.GestaoPedidos/RealizarPedido',
            pedidos__pb2.RealizarPedidoRequest.SerializeToString,
            pedidos__pb2.RealizarPedidoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecuperarHistoricoPedidos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pedidos.GestaoPedidos/RecuperarHistoricoPedidos',
            pedidos__pb2.HistoricoPedidosRequest.SerializeToString,
            pedidos__pb2.HistoricoPedidosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterDetalhesPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pedidos.GestaoPedidos/ObterDetalhesPedido',
            pedidos__pb2.ObterDetalhesPedidoRequest.SerializeToString,
            pedidos__pb2.ObterDetalhesPedidoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
