# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autenticacao.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61utenticacao.proto\x12\x0c\x61utenticacao\"E\n\x17RegistrarUsuarioRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\r\n\x05senha\x18\x03 \x01(\t\"&\n\x18RegistrarUsuarioResponse\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x13LoginUsuarioRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05senha\x18\x02 \x01(\t\"%\n\x14LoginUsuarioResponse\x12\r\n\x05token\x18\x01 \x01(\t2\xcf\x01\n\x13\x41utenticacaoUsuario\x12\x61\n\x10RegistrarUsuario\x12%.autenticacao.RegistrarUsuarioRequest\x1a&.autenticacao.RegistrarUsuarioResponse\x12U\n\x0cLoginUsuario\x12!.autenticacao.LoginUsuarioRequest\x1a\".autenticacao.LoginUsuarioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autenticacao_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTRARUSUARIOREQUEST']._serialized_start=36
  _globals['_REGISTRARUSUARIOREQUEST']._serialized_end=105
  _globals['_REGISTRARUSUARIORESPONSE']._serialized_start=107
  _globals['_REGISTRARUSUARIORESPONSE']._serialized_end=145
  _globals['_LOGINUSUARIOREQUEST']._serialized_start=147
  _globals['_LOGINUSUARIOREQUEST']._serialized_end=198
  _globals['_LOGINUSUARIORESPONSE']._serialized_start=200
  _globals['_LOGINUSUARIORESPONSE']._serialized_end=237
  _globals['_AUTENTICACAOUSUARIO']._serialized_start=240
  _globals['_AUTENTICACAOUSUARIO']._serialized_end=447
# @@protoc_insertion_point(module_scope)
