# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import autenticacao_pb2 as autenticacao__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in autenticacao_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AutenticacaoUsuarioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarUsuario = channel.unary_unary(
                '/autenticacao.AutenticacaoUsuario/RegistrarUsuario',
                request_serializer=autenticacao__pb2.RegistrarUsuarioRequest.SerializeToString,
                response_deserializer=autenticacao__pb2.RegistrarUsuarioResponse.FromString,
                _registered_method=True)
        self.LoginUsuario = channel.unary_unary(
                '/autenticacao.AutenticacaoUsuario/LoginUsuario',
                request_serializer=autenticacao__pb2.LoginUsuarioRequest.SerializeToString,
                response_deserializer=autenticacao__pb2.LoginUsuarioResponse.FromString,
                _registered_method=True)


class AutenticacaoUsuarioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegistrarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutenticacaoUsuarioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarUsuario,
                    request_deserializer=autenticacao__pb2.RegistrarUsuarioRequest.FromString,
                    response_serializer=autenticacao__pb2.RegistrarUsuarioResponse.SerializeToString,
            ),
            'LoginUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginUsuario,
                    request_deserializer=autenticacao__pb2.LoginUsuarioRequest.FromString,
                    response_serializer=autenticacao__pb2.LoginUsuarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autenticacao.AutenticacaoUsuario', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autenticacao.AutenticacaoUsuario', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AutenticacaoUsuario(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegistrarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autenticacao.AutenticacaoUsuario/RegistrarUsuario',
            autenticacao__pb2.RegistrarUsuarioRequest.SerializeToString,
            autenticacao__pb2.RegistrarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autenticacao.AutenticacaoUsuario/LoginUsuario',
            autenticacao__pb2.LoginUsuarioRequest.SerializeToString,
            autenticacao__pb2.LoginUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
