# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import catalogo_pb2 as catalogo__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in catalogo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CatalogoLivrosStub(object):
    """Serviço de catálogo de livros
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarLivro = channel.unary_unary(
                '/catalogo.CatalogoLivros/ConsultarLivro',
                request_serializer=catalogo__pb2.ConsultarLivroRequest.SerializeToString,
                response_deserializer=catalogo__pb2.ConsultarLivroResponse.FromString,
                _registered_method=True)
        self.ListarLivros = channel.unary_unary(
                '/catalogo.CatalogoLivros/ListarLivros',
                request_serializer=catalogo__pb2.ListarLivrosRequest.SerializeToString,
                response_deserializer=catalogo__pb2.ListarLivrosResponse.FromString,
                _registered_method=True)
        self.ObterDetalhesLivro = channel.unary_unary(
                '/catalogo.CatalogoLivros/ObterDetalhesLivro',
                request_serializer=catalogo__pb2.ConsultarLivroRequest.SerializeToString,
                response_deserializer=catalogo__pb2.ConsultarLivroResponse.FromString,
                _registered_method=True)
        self.AtualizarLivro = channel.unary_unary(
                '/catalogo.CatalogoLivros/AtualizarLivro',
                request_serializer=catalogo__pb2.AtualizarLivroRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class CatalogoLivrosServicer(object):
    """Serviço de catálogo de livros
    """

    def ConsultarLivro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarLivros(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterDetalhesLivro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarLivro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogoLivrosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarLivro': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarLivro,
                    request_deserializer=catalogo__pb2.ConsultarLivroRequest.FromString,
                    response_serializer=catalogo__pb2.ConsultarLivroResponse.SerializeToString,
            ),
            'ListarLivros': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarLivros,
                    request_deserializer=catalogo__pb2.ListarLivrosRequest.FromString,
                    response_serializer=catalogo__pb2.ListarLivrosResponse.SerializeToString,
            ),
            'ObterDetalhesLivro': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterDetalhesLivro,
                    request_deserializer=catalogo__pb2.ConsultarLivroRequest.FromString,
                    response_serializer=catalogo__pb2.ConsultarLivroResponse.SerializeToString,
            ),
            'AtualizarLivro': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarLivro,
                    request_deserializer=catalogo__pb2.AtualizarLivroRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalogo.CatalogoLivros', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalogo.CatalogoLivros', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogoLivros(object):
    """Serviço de catálogo de livros
    """

    @staticmethod
    def ConsultarLivro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogo.CatalogoLivros/ConsultarLivro',
            catalogo__pb2.ConsultarLivroRequest.SerializeToString,
            catalogo__pb2.ConsultarLivroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarLivros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogo.CatalogoLivros/ListarLivros',
            catalogo__pb2.ListarLivrosRequest.SerializeToString,
            catalogo__pb2.ListarLivrosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterDetalhesLivro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogo.CatalogoLivros/ObterDetalhesLivro',
            catalogo__pb2.ConsultarLivroRequest.SerializeToString,
            catalogo__pb2.ConsultarLivroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarLivro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogo.CatalogoLivros/AtualizarLivro',
            catalogo__pb2.AtualizarLivroRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
